version: "3"
services:
  redis:
    image: redis:5.0-alpine
    restart: always
    ports:
      - "6379:6379"
  postgres:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=eshop_db
      - POSTGRES_USER=eshop_user
      - POSTGRES_PASSWORD=password
    container_name: eshop_postgres
  mongodb:
    image: mongo:4.0.20
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb/data:/var/lib/mongodb/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    container_name: eshop_mongodb
  rabbitmq:
    image: rabbitmq:3.8.9-alpine
    restart: always
    ports:
      - "5672:5672"
    volumes:
      - ./data/rabbitmq/data:/var/lib/rabbitmq/data
    container_name: eshop_rabbitmq
  backend:
    depends_on:
      - postgres
      - cartservice
      - rabbitmq
    image: 306798326015.dkr.ecr.us-east-1.amazonaws.com/eshop/backend:0.0.3
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://eshop_postgres:5432/eshop_db
      - URL_CARTSERVICE=http://eshopcartservice:8091
      - URL_PRODUCTSERVICE=http://eshopproductservice:8092
      - SPRING_RABBITMQ_HOST=rabbitmq
    container_name: eshopbackend
  frontend:
     depends_on:
       - backend
     image: 306798326015.dkr.ecr.us-east-1.amazonaws.com/eshop/frontend:0.0.1
     ports:
       - "8080:8080"
     container_name: eshopfrontend
  cartservice:
    depends_on:
      - redis
      - rabbitmq
    image: 306798326015.dkr.ecr.us-east-1.amazonaws.com/eshop-cartservice:0.0.2
    restart : always
    ports:
      - "8091:8091"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_RABBITMQ_HOST=rabbitmq
    container_name: eshopcartservice
  productservice:
    depends_on:
      - mongodb
    image: 306798326015.dkr.ecr.us-east-1.amazonaws.com/eshop-productservice:0.0.2
    restart : always
    ports:
      - "8092:8092"
    environment:
      - PORT=8092
      - MONGO_URI=mongodb://admin:password@mongodb
      - INIT_DATA=true
    container_name: eshopproductservice
  recommendservice:
    depends_on:
      - productservice
    image: 306798326015.dkr.ecr.us-east-1.amazonaws.com/eshop-recommendservice:0.0.1
    environment:
      - URL_PRODUCTSERVICE=http://eshopproductservice:8092
    ports:
      - "8093:8093"
    container_name: eshoprecommendservice
  currencyservice:
    image: 306798326015.dkr.ecr.us-east-1.amazonaws.com/eshop-currencyservice:0.0.1
    ports:
      - "8094:8094"
    container_name: eshopcurrencyservice
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    container_name: eshop_nginx_ingress
    depends_on:
      - frontend
      - backend
      - cartservice
      - productservice
      - recommendservice
      - currencyservice
      